export const FREE_SIX_DIGITS_HASHES_REDIS_KEY = 'FREE_SIX_DIGITS_HASHES_KEY';

export const USED_HASHES_TO_UPDATE_REDIS_KEY = 'USED_HASHES_TO_UPDATE_KEY';

export const LINK_CREATED_EVENT_NAME = 'link.created';
